export interface Exercise {
  id: string;
  name: string;
  muscle: string;
  target: string;
  sets: number;
  reps: string;
  mediaType: "video" | "gif" | "image";
  mediaSource: { uri: string } | number; // Remote object or local require()
  tip: string;
  setupSteps: string[];
  mistakes: string[];
}

export interface MuscleGroup {
  id: string;
  label: string;
}

export const MUSCLE_GROUPS: MuscleGroup[] = [
  { id: "chest", label: "Chest" },
  { id: "back", label: "Back" },
  { id: "shoulders", label: "Shoulders" },
  { id: "biceps", label: "Biceps" },
  { id: "triceps", label: "Triceps" },
  { id: "abs", label: "Abs" },
  { id: "legs", label: "Legs" },
];

const FREE_EXERCISE_DB =
  "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises";

export const EXERCISE_DATABASE: Record<string, Exercise[]> = {
  chest: [
    {
      id: "c1",
      name: "Barbell Bench Press",
      muscle: "chest",
      target: "Mid Chest & Power",
      sets: 3,
      reps: "8-10",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press/0.gif",
      },
      tip: "Keep your feet flat on the floor. Let your back bend a little.",
      setupSteps: [
        "Lie down flat on the bench. Your eyes should be under the bar.",
        "Hold the bar a little wider than your shoulders.",
        "Lift the bar off the rack. Slowly bring it down to your chest.",
        "Push the bar up fast until your arms are straight.",
      ],
      mistakes: [
        "Do not bounce the bar on your chest",
        "Do not open your elbows out to the side",
      ],
    },
    {
      id: "c2",
      name: "Dumbbell Bench Press",
      muscle: "chest",
      target: "Mid Chest & Balance",
      sets: 3,
      reps: "10-12",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.gif",
      },
      tip: "Keep your elbows close to your body, not out wide.",
      setupSteps: [
        "Sit on the bench. Rest the dumbbells on your legs.",
        "Lie back on the bench. Bring the dumbbells up with you.",
        "Push the dumbbells straight up over your chest.",
        "Slowly bring them down to chest level.",
      ],
      mistakes: [
        "Do not bang the dumbbells together at the top",
        "Do not drop the weight down fast",
      ],
    },
    {
      id: "c3",
      name: "Incline Barbell Press",
      muscle: "chest",
      target: "Upper Chest",
      sets: 3,
      reps: "8-10",
      mediaType: "gif",
      mediaSource: {
        uri: "${FREE_EXERCISE_DB}/Barbell_Incline_Bench_Press/0.gif",
      },
      tip: "Set the bench at a slight angle, not too steep.",
      setupSteps: [
        "Set the bench at a slight upward angle.",
        "Slowly bring the bar down near your collarbone.",
        "Push the bar back up over your eyes.",
      ],
      mistakes: [
        "Do not set the bench too high, or it will work your shoulders instead",
      ],
    },
    {
      id: "c4",
      name: "Incline Dumbbell Press",
      muscle: "chest",
      target: "Upper Chest Focus",
      sets: 3,
      reps: "10-12",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Incline_Bench_Press/0.gif",
      },
      tip: "Keep your chest lifted up the whole time.",
      setupSteps: [
        "Lie back on the angled bench.",
        "Push the weights up. Do not lock your elbows hard.",
        "Slowly bring the weights back down to chest level.",
      ],
      mistakes: ["Do not lift your lower back off the bench"],
    },
    {
      id: "c5",
      name: "Decline Bench Press",
      muscle: "chest",
      target: "Lower Chest",
      sets: 3,
      reps: "10-12",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Decline_Bench_Press/0.gif",
      },
      tip: "Lock your legs under the pad before you lift the weight.",
      setupSteps: [
        "Hook your legs under the pads on the decline bench.",
        "Lift the bar and bring it down to your lower chest.",
        "Push the bar straight back up.",
      ],
      mistakes: ["Do not let your legs come loose during the set"],
    },
    {
      id: "c6",
      name: "Chest Press Machine",
      muscle: "chest",
      target: "Overall Chest (Guided)",
      sets: 3,
      reps: "10-12",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Chest_Press/0.gif",
      },
      tip: "Set the seat so the handles are level with your chest.",
      setupSteps: [
        "Adjust the seat to the right height.",
        "Hold the handles. Keep your back flat on the pad.",
        "Push forward until your arms are straight.",
      ],
      mistakes: ["Do not lift your shoulders up while pushing"],
    },
    {
      id: "c7",
      name: "Machine Chest Fly (Pec Deck)",
      muscle: "chest",
      target: "Inner & Outer Chest Isolation",
      sets: 3,
      reps: "12-15",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Butterfly/0.gif",
      },
      tip: "Bring the handles together and hold for 1 second.",
      setupSteps: [
        "Sit back on the pad. Open your arms out wide.",
        "Bring the handles together in front of your chest. Keep a small bend in your elbows.",
        "Slowly open your arms back out until you feel a stretch.",
      ],
      mistakes: ["Do not bend your elbows too much during the move"],
    },
    {
      id: "c8",
      name: "Hammer Strength Chest Press",
      muscle: "chest",
      target: "Mid/Upper Chest Isolation",
      sets: 3,
      reps: "10-12",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leverage_Incline_Chest_Press/0.gif",
      },
      tip: "This is a safe way to press heavy without needing help.",
      setupSteps: [
        "Put weight plates on the machine.",
        "Sit with your back flat on the pad.",
        "Push the handles forward slowly and smoothly.",
      ],
      mistakes: ["Do not lift your shoulders up near your ears"],
    },
    {
      id: "c9",
      name: "Chest Dips",
      muscle: "chest",
      target: "Lower Chest & Triceps",
      sets: 3,
      reps: "8-10",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chest_Dip/0.gif",
      },
      tip: "Lean your body forward a little to work the chest more.",
      setupSteps: [
        "Hold the dip bars and lift your body up.",
        "Lean your chest forward a little.",
        "Lower your body until your arms are level with the floor.",
        "Push yourself back up to the start.",
      ],
      mistakes: ["Do not stay fully upright, or it will only work your arms"],
    },
    {
      id: "c10",
      name: "Push-ups",
      muscle: "chest",
      target: "Core & Chest Bodyweight",
      sets: 3,
      reps: "12-15",
      mediaType: "gif",
      mediaSource: {
        uri: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-up/0.gif",
      },
      tip: "Keep your body straight from head to feet.",
      setupSteps: [
        "Put your hands on the floor, a little wider than your shoulders.",
        "Lower your body until your chest is close to the floor.",
        "Push yourself back up to the top.",
      ],
      mistakes: ["Do not let your hips drop down"],
    },
    {
      id: "c11",
      name: "Dumbbell Flyes",
      muscle: "chest",
      target: "Chest Stretch & Isolation",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Dumbbell_Flyes/0.jpg`,
      },
      tip: "Keep a soft bend in your elbows throughout the movement.",
      setupSteps: [
        "Lie on a flat bench holding dumbbells above your chest.",
        "Lower weights in a wide arc until you feel a comfortable stretch in your chest.",
        "Squeeze chest muscles to bring dumbbells back to starting position.",
      ],
      mistakes: ["Do not bend elbows too much turning it into a press"],
    },
    {
      id: "c12",
      name: "Cable Crossover",
      muscle: "chest",
      target: "Lower & Inner Chest",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Cable_Crossover/0.jpg`,
      },
      tip: "Cross your hands slightly at the bottom for maximal squeeze.",
      setupSteps: [
        "Set pulleys at high position and grab handles.",
        "Step forward slightly with one foot for balance.",
        "Bring handles down and together in front of your waist.",
      ],
      mistakes: ["Do not swing your upper body to pull handles"],
    },
  ],

  back: [
    {
      id: "b1",
      name: "Bent Over Barbell Row",
      muscle: "back",
      target: "Middle Back & Lats",
      sets: 3,
      reps: "8-10",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Bent_Over_Barbell_Row/0.jpg` },
      tip: "Keep your head up and your back flat. Do not curve your back.",
      setupSteps: [
        "Bend forward at your hips. Bend your knees a little. Your body should be almost flat like a table.",
        "Let the bar hang below your shoulders. Keep your arms straight.",
        "Pull the bar up to your lower chest. Squeeze your shoulder blades together.",
        "Slowly bring the bar back down.",
      ],
      mistakes: [
        "Do not curve your lower back",
        "Do not jerk the weight up fast",
      ],
    },
    {
      id: "b2",
      name: "Bent Over Two-Dumbbell Row",
      muscle: "back",
      target: "Middle Back (Dumbbell)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Bent_Over_Two-Dumbbell_Row/0.jpg`,
      },
      tip: "Keep your elbows close to your body when you pull.",
      setupSteps: [
        "Hold a dumbbell in each hand. Bend forward with a flat back.",
        "Let both arms hang down straight.",
        "Pull both dumbbells up to your chest at the same time.",
        "Slowly lower them back down.",
      ],
      mistakes: [
        "Do not stand too straight, it becomes a shrug",
        "Do not use your lower back to jerk the weight up",
      ],
    },
    {
      id: "b3",
      name: "Band Assisted Pull-Up",
      muscle: "back",
      target: "Lats (Beginner-Friendly)",
      sets: 3,
      reps: "6-10",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Band_Assisted_Pull-Up/0.jpg` },
      tip: "Good choice if a normal pull-up is too hard for you right now.",
      setupSteps: [
        "Tie a resistance band around the pull-up bar.",
        "Put one knee or foot inside the band.",
        "Pull yourself up until your chin is above the bar.",
        "Slowly come back down until your arms are straight.",
      ],
      mistakes: [
        "Do not use a band so strong that it does all the work",
        "Do not swing your body instead of pulling",
      ],
    },
    {
      id: "b4",
      name: "Bodyweight Mid Row",
      muscle: "back",
      target: "Middle Back (No Equipment)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Bodyweight_Mid_Row/0.jpg` },
      tip: "Move your feet to change the difficulty. A flatter body position is harder.",
      setupSteps: [
        "Hold a bar at hip height. Lean back with straight arms.",
        "Keep your body straight and stiff.",
        "Pull your chest up to the bar. Push your elbows back.",
        "Slowly go back down until your arms are straight.",
      ],
      mistakes: [
        "Do not let your hips drop",
        "Do not pull with only your arms, use your back too",
      ],
    },
    {
      id: "b5",
      name: "Bent Over One-Arm Long Bar Row",
      muscle: "back",
      target: "Middle Back (Unilateral)",
      sets: 3,
      reps: "10 each side",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Bent_Over_One-Arm_Long_Bar_Row/0.jpg`,
      },
      tip: "Doing one side at a time helps make both sides equally strong.",
      setupSteps: [
        "Fix one end of the bar in a corner or a landmine holder.",
        "Stand over the bar. Bend forward. Hold the bar behind the weight plates.",
        "Pull the bar up to your chest. Move your elbow back.",
        "Slowly lower it down. Do the same on the other side.",
      ],
      mistakes: [
        "Do not twist your body to lift the weight",
        "Do not let the bar fall down fast",
      ],
    },
    {
      id: "b6",
      name: "Bent-Arm Barbell Pullover",
      muscle: "back",
      target: "Lats & Chest Stretch",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Bent-Arm_Barbell_Pullover/0.jpg`,
      },
      tip: "Move slowly. This exercise is about a good stretch, not speed.",
      setupSteps: [
        "Lie flat on the bench. Hold the bar above your chest with bent arms.",
        "Keep your arms bent the same way. Bring the bar back over your head until you feel a stretch.",
        "Pull the bar back up over your chest using your back muscles.",
      ],
      mistakes: [
        "Do not use too much weight, you may lose control",
        "Do not straighten your arms during the move",
      ],
    },
    {
      id: "b7",
      name: "Barbell Deadlift",
      muscle: "back",
      target: "Lower Back, Hamstrings & Glutes",
      sets: 3,
      reps: "6-8",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Deadlift/0.jpg` },
      tip: "This is a great strength exercise. Start with light weight and focus on good form.",
      setupSteps: [
        "Stand with the bar close to your feet. Feet should be hip-width apart.",
        "Bend down and hold the bar just outside your legs. Keep your back flat.",
        "Push through your heels and stand up tall. Keep the bar close to your body.",
        "Bend at your hips first to bring the bar back down.",
      ],
      mistakes: [
        "Do not curve your lower back",
        "Do not let the bar move away from your legs",
      ],
    },
    {
      id: "b8",
      name: "Bent Over Two-Arm Long Bar Row",
      muscle: "back",
      target: "Middle Back (Landmine Row)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Bent_Over_Two-Arm_Long_Bar_Row/0.jpg`,
      },
      tip: "Good choice if your gym does not have a cable row machine.",
      setupSteps: [
        "Fix one end of the bar in a corner or landmine holder.",
        "Stand over the bar. Bend forward with a flat back. Hold it with both hands.",
        "Pull the bar up to your chest. Squeeze your shoulder blades.",
        "Slowly lower it back down.",
      ],
      mistakes: [
        "Do not stand too straight",
        "Do not let the weight hit the floor hard",
      ],
    },
    {
      id: "b9",
      name: "Lat Pulldown",
      muscle: "back",
      target: "Upper Back & Lats",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Cable_Wide-Grip_Lat_Pulldown/0.jpg`,
      },
      tip: "Pull with your elbows driving straight down to your sides.",
      setupSteps: [
        "Sit at machine with thighs snug under pads.",
        "Grip bar wider than shoulder width.",
        "Pull bar down to upper chest while leaning back slightly.",
      ],
      mistakes: ["Do not pull the bar behind your neck"],
    },
    {
      id: "b10",
      name: "Seated Cable Row",
      muscle: "back",
      target: "Middle Back Thickness",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Cable_Seated_Row/0.jpg`,
      },
      tip: "Avoid leaning back too far as you pull the handles.",
      setupSteps: [
        "Sit with feet on footrests and knees slightly bent.",
        "Grip handles and keep torso erect.",
        "Pull handle toward belly button squeezing shoulder blades together.",
      ],
      mistakes: ["Do not rock your torso backward and forward"],
    },
  ],

  shoulders: [
    {
      id: "s1",
      name: "Barbell Shoulder Press",
      muscle: "shoulders",
      target: "Overall Shoulders",
      sets: 3,
      reps: "8-10",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Shoulder_Press/0.jpg` },
      tip: "Keep your stomach tight so your back does not bend too much.",
      setupSteps: [
        "Sit or stand. Hold the bar at shoulder level with palms facing forward.",
        "Push the bar straight up until your arms are straight.",
        "Slowly bring the bar back down to your shoulders.",
      ],
      mistakes: [
        "Do not lean back too much to push the weight up",
        "Do not open your elbows out too wide",
      ],
    },
    {
      id: "s2",
      name: "Arnold Dumbbell Press",
      muscle: "shoulders",
      target: "Full Deltoid Range",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Arnold_Dumbbell_Press/0.jpg` },
      tip: "Turning your hands during the press works your shoulder from more angles.",
      setupSteps: [
        "Hold dumbbells in front of your shoulders. Palms should face you.",
        "Push up while you turn your palms to face forward.",
        "Turn your palms back as you bring the weights down.",
      ],
      mistakes: [
        "Do not turn your hands too fast",
        "Do not use weight too heavy to turn properly",
      ],
    },
    {
      id: "s3",
      name: "Alternating Deltoid Raise",
      muscle: "shoulders",
      target: "Front & Side Delts",
      sets: 3,
      reps: "10-12 each side",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Alternating_Deltoid_Raise/0.jpg`,
      },
      tip: "Use light weight. This move is for shaping, not for heavy lifting.",
      setupSteps: [
        "Stand and hold a dumbbell in each hand by your sides.",
        "Lift one arm to the front, up to shoulder height. Then bring it down.",
        "Lift the same arm out to the side, up to shoulder height. Then bring it down.",
        "Do the same with the other arm.",
      ],
      mistakes: [
        "Do not swing the weight up fast",
        "Do not lift your shoulders up to your ears",
      ],
    },
    {
      id: "s4",
      name: "Barbell Incline Shoulder Raise",
      muscle: "shoulders",
      target: "Front Delts",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Barbell_Incline_Shoulder_Raise/0.jpg`,
      },
      tip: "Keep your arms straight the whole time. This works the front of your shoulder.",
      setupSteps: [
        "Lie on your back on the angled bench. Hold the bar with straight arms.",
        "Lift the bar up by raising your shoulders. Keep your arms straight.",
        "Slowly bring it back down.",
      ],
      mistakes: [
        "Do not bend your elbows to help lift",
        "Do not use weight that is too heavy",
      ],
    },
    {
      id: "s5",
      name: "Bent Over Dumbbell Rear Delt Raise",
      muscle: "shoulders",
      target: "Rear Delts",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg`,
      },
      tip: "People often forget this muscle. This move works it directly.",
      setupSteps: [
        "Lean forward. Rest your head on the bench to stay steady.",
        "Let the dumbbells hang down. Palms should face each other.",
        "Lift both arms out to the side until they are level with the floor.",
        "Slowly bring them back down.",
      ],
      mistakes: [
        "Do not swing your body to lift the weight",
        "Do not move your arms too far back, lift them to the side",
      ],
    },
    {
      id: "s6",
      name: "Band Pull Apart",
      muscle: "shoulders",
      target: "Rear Delts & Shoulder Health",
      sets: 3,
      reps: "15-20",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Band_Pull_Apart/0.jpg` },
      tip: "A great warm-up move. It is safe and easy for beginners.",
      setupSteps: [
        "Hold a band with both hands. Stretch your arms out in front of you.",
        "Pull the band apart by moving your hands to the sides.",
        "Squeeze your shoulder blades together at the end.",
        "Slowly go back to the start.",
      ],
      mistakes: [
        "Do not bend your elbows while pulling",
        "Do not use a band that is too easy",
      ],
    },
    {
      id: "s7",
      name: "Alternating Cable Shoulder Press",
      muscle: "shoulders",
      target: "Shoulders (Cable Stability)",
      sets: 3,
      reps: "10-12 each side",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Alternating_Cable_Shoulder_Press/0.jpg`,
      },
      tip: "The cable machine makes this harder to balance than dumbbells.",
      setupSteps: [
        "Set both cables to the bottom. Hold a handle in each hand at shoulder height.",
        "Push one arm straight up. Keep your chest up.",
        "Bring it back down. Do the same with the other arm.",
      ],
      mistakes: [
        "Do not lean to one side to push the weight",
        "Do not switch sides too fast",
      ],
    },
    {
      id: "s8",
      name: "Barbell Rear Delt Row",
      muscle: "shoulders",
      target: "Rear Delts (Compound)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Rear_Delt_Row/0.jpg` },
      tip: "This is like a bench press in reverse. Use your shoulder muscles, not your arms, to pull.",
      setupSteps: [
        "Bend forward. Hold the bar with a wide grip. Your body should be almost flat.",
        "Open your elbows out. Pull the bar up to your upper chest.",
        "Squeeze at the top. Then slowly bring it back down.",
      ],
      mistakes: [
        "Do not lift the weight with your arm muscles",
        "Do not stand too straight",
      ],
    },
    {
      id: "s9",
      name: "Side Lateral Raise",
      muscle: "shoulders",
      target: "Side Delts",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Side_Lateral_Raise/0.jpg`,
      },
      tip: "Lead with your elbows and tilt pinkies slightly up at top.",
      setupSteps: [
        "Stand holding dumbbells at your sides.",
        "Raise arms out to sides until parallel to floor.",
        "Lower back down slowly under control.",
      ],
      mistakes: ["Do not shrug your shoulders up while lifting"],
    },
    {
      id: "s10",
      name: "Barbell Upright Row",
      muscle: "shoulders",
      target: "Traps & Delts",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Upright_Barbell_Row/0.jpg`,
      },
      tip: "Keep the bar close to your body during the entire movement.",
      setupSteps: [
        "Grip barbell with palms facing you, narrower than shoulder width.",
        "Pull bar straight up toward chin leading with elbows.",
        "Lower bar back down slowly.",
      ],
      mistakes: [
        "Do not raise elbows higher than your shoulders if uncomfortable",
      ],
    },
  ],

  biceps: [
    {
      id: "bi1",
      name: "Barbell Curl",
      muscle: "biceps",
      target: "Overall Biceps",
      sets: 3,
      reps: "8-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Curl/0.jpg` },
      tip: "Only your lower arms should move. Keep your upper arms close to your body.",
      setupSteps: [
        "Stand and hold the bar with your palms facing up. Hands should be shoulder-width apart.",
        "Lift the bar up to your shoulders. Squeeze your arm muscles.",
        "Slowly bring the bar back down until your arms are straight.",
      ],
      mistakes: [
        "Do not swing your body to lift the weight",
        "Do not stop before your arms are fully straight",
      ],
    },
    {
      id: "bi2",
      name: "Alternate Hammer Curl",
      muscle: "biceps",
      target: "Biceps & Forearms",
      sets: 3,
      reps: "10-12 each arm",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Alternate_Hammer_Curl/0.jpg` },
      tip: "This grip also works your lower arms more than a normal curl.",
      setupSteps: [
        "Hold a dumbbell in each hand. Palms should face your body.",
        "Lift one dumbbell up to your shoulder. Keep your palm facing in.",
        "Bring it back down. Do the same with the other arm.",
      ],
      mistakes: [
        "Do not let your elbow move away from your body",
        "Do not use speed to lift the weight, lift it slowly",
      ],
    },
    {
      id: "bi3",
      name: "Alternate Incline Dumbbell Curl",
      muscle: "biceps",
      target: "Biceps (Extra Stretch)",
      sets: 3,
      reps: "10-12 each arm",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Alternate_Incline_Dumbbell_Curl/0.jpg`,
      },
      tip: "This position gives your arm muscle a deeper stretch than standing curls.",
      setupSteps: [
        "Sit back on the angled bench. Hold a dumbbell in each hand. Let your arms hang down.",
        "Lift one dumbbell up. Turn your palm to face up as you lift.",
        "Slowly bring it back down. Do the same on the other side.",
      ],
      mistakes: [
        "Do not lift your shoulder off the bench",
        "Do not bring the weight down too fast",
      ],
    },
    {
      id: "bi4",
      name: "Barbell Curls Lying Against An Incline",
      muscle: "biceps",
      target: "Biceps (Strict Isolation)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Barbell_Curls_Lying_Against_An_Incline/0.jpg`,
      },
      tip: "Leaning on the bench stops you from using your back to cheat.",
      setupSteps: [
        "Lie with your chest against the angled bench. Hold the bar with your arms hanging straight down.",
        "Lift the bar up as high as you can. Do not move your upper arms.",
        "Slowly bring it back down.",
      ],
      mistakes: [
        "Do not stop early, go all the way down",
        "Do not hold the bar too wide or too narrow",
      ],
    },
    {
      id: "bi5",
      name: "Concentration Curls",
      muscle: "biceps",
      target: "Biceps Peak",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Concentration_Curls/0.jpg`,
      },
      tip: "Rest your triceps against your inner thigh to lock posture.",
      setupSteps: [
        "Sit on bench, hold dumbbell in one hand.",
        "Rest elbow against inner thigh.",
        "Curl dumbbell up toward chest and squeeze.",
      ],
      mistakes: ["Do not swing your torso during curl"],
    },
    {
      id: "bi6",
      name: "Preacher Curl",
      muscle: "biceps",
      target: "Lower Biceps Isolation",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Preacher_Curl/0.jpg`,
      },
      tip: "Keep triceps flush on the pad at all times.",
      setupSteps: [
        "Sit at preacher bench, resting arms over pad.",
        "Hold barbell with underhand grip.",
        "Curl bar upward towards shoulders, then slowly lower.",
      ],
      mistakes: ["Do not fully snap elbows locked at the bottom"],
    },
  ],

  triceps: [
    {
      id: "t1",
      name: "Bench Dips",
      muscle: "triceps",
      target: "Triceps (No Equipment)",
      sets: 3,
      reps: "10-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Bench_Dips/0.jpg` },
      tip: "Keep your hips close to the bench. If they move forward, it works your shoulders instead.",
      setupSteps: [
        "Sit on the edge of a bench. Hold the edge with your hands beside your hips.",
        "Walk your feet forward. Lower your body by bending your elbows.",
        "Push back up until your arms are straight.",
      ],
      mistakes: [
        "Do not let your elbows point out wide",
        "Do not go down too far, it can hurt your shoulders",
      ],
    },
    {
      id: "t2",
      name: "Band Skull Crusher",
      muscle: "triceps",
      target: "Triceps (Overhead)",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Band_Skull_Crusher/0.jpg` },
      tip: "A safer choice for beginners, because there is no bar near your face.",
      setupSteps: [
        "Tie a band above you. Lie on a bench with the band above your head.",
        "Hold the band. Bend your elbows. Your upper arms should point straight up.",
        "Straighten your arms by moving only your elbows.",
        "Slowly go back to the start.",
      ],
      mistakes: [
        "Do not let your upper arms move, keep them still",
        "Do not use a band that is too light",
      ],
    },
    {
      id: "t3",
      name: "Body Tricep Press",
      muscle: "triceps",
      target: "Triceps (Bodyweight)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Body_Tricep_Press/0.jpg` },
      tip: "Good choice when the dip bar or bench is being used.",
      setupSteps: [
        "Set a bar at chest height. Hold it and step back so you lean on it.",
        "Bend your elbows to bring your body toward the bar.",
        "Push back up by straightening your elbows.",
      ],
      mistakes: [
        "Do not let your hips drop down",
        "Do not make the movement too small",
      ],
    },
    {
      id: "t4",
      name: "Body-Up",
      muscle: "triceps",
      target: "Triceps (Plank Press)",
      sets: 3,
      reps: "8-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Body-Up/0.jpg` },
      tip: "Keep your stomach tight the whole time. This is like a plank.",
      setupSteps: [
        "Hold a plank. Your weight should be on your lower arms and toes.",
        "Push your hands into the floor. Straighten your elbows to lift your body up.",
        "Slowly lower back down onto your lower arms.",
      ],
      mistakes: [
        "Do not let your hips go up or down too much",
        "Do not go down too fast, go slowly",
      ],
    },
    {
      id: "t5",
      name: "Board Press",
      muscle: "triceps",
      target: "Triceps (Compound Press)",
      sets: 3,
      reps: "6-8",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Board_Press/0.jpg` },
      tip: "This shorter movement works your arm muscles more than a normal bench press.",
      setupSteps: [
        "Lie on the bench. Hold the bar at shoulder-width or a little closer.",
        "Bring the bar down until it touches the boards on your chest.",
        "Push the bar back up until your arms are straight.",
      ],
      mistakes: [
        "Do not open your elbows out wide",
        "Do not bounce the bar on the boards",
      ],
    },
    {
      id: "t6",
      name: "Triceps Pushdown",
      muscle: "triceps",
      target: "Triceps Lateral Head",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Cable_Pushdown/0.jpg`,
      },
      tip: "Pin your elbows to your sides throughout the set.",
      setupSteps: [
        "Attach bar or rope to high pulley.",
        "Hold with palms facing down or together.",
        "Push handle down until arms are fully extended.",
      ],
      mistakes: ["Do not let your shoulders roll forward"],
    },
    {
      id: "t7",
      name: "Standing Dumbbell Triceps Extension",
      muscle: "triceps",
      target: "Triceps Long Head",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Standing_Dumbbell_Triceps_Extension/0.jpg`,
      },
      tip: "Keep upper arms pointing up close to your ears.",
      setupSteps: [
        "Stand holding a dumbbell with both hands over your head.",
        "Lower weight behind head by bending elbows.",
        "Extend arms back to starting position overhead.",
      ],
      mistakes: ["Do not flare elbows out wide"],
    },
  ],

  abs: [
    {
      id: "a1",
      name: "Ab Crunch Machine",
      muscle: "abs",
      target: "Upper Abs (Guided)",
      sets: 3,
      reps: "15-20",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Ab_Crunch_Machine/0.jpg` },
      tip: "Start with light weight. Feel your stomach doing the work, not your arms.",
      setupSteps: [
        "Sit in the machine. Put your feet under the pads and hold the handles.",
        "Bend your body forward. Breathe out as you squeeze your stomach.",
        "Slowly go back to the start.",
      ],
      mistakes: [
        "Do not pull with your arms, use your stomach",
        "Do not move too fast without a real squeeze",
      ],
    },
    {
      id: "a2",
      name: "Ab Roller",
      muscle: "abs",
      target: "Full Core",
      sets: 3,
      reps: "8-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Ab_Roller/0.jpg` },
      tip: "Start with small movements. This exercise is harder than it looks.",
      setupSteps: [
        "Kneel on the floor. Hold the ab roller with both hands.",
        "Slowly roll forward. Go as far as you can control.",
        "Pull yourself back to the start. Keep your stomach tight.",
      ],
      mistakes: [
        "Do not let your lower back drop down",
        "Do not roll out too far to come back",
      ],
    },
    {
      id: "a3",
      name: "Air Bike",
      muscle: "abs",
      target: "Abs & Obliques",
      sets: 3,
      reps: "15-20 each side",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Air_Bike/0.jpg` },
      tip: "Move slowly and correctly. A full twist matters more than speed.",
      setupSteps: [
        "Lie on your back. Put your hands lightly behind your head. Lift your knees up.",
        "Bring one elbow to the opposite knee. Straighten your other leg out.",
        "Switch sides like you are pedaling a bike.",
      ],
      mistakes: [
        "Do not pull your neck with your hands",
        "Do not rush without a real twist",
      ],
    },
    {
      id: "a4",
      name: "Alternate Heel Touchers",
      muscle: "abs",
      target: "Obliques",
      sets: 3,
      reps: "15-20 each side",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Alternate_Heel_Touchers/0.jpg` },
      tip: "An easy way for beginners to work the side stomach muscles.",
      setupSteps: [
        "Lie on your back. Bend your knees, feet on the floor. Arms by your sides.",
        "Curl up and to one side to touch that heel.",
        "Go back to the start. Do the same on the other side.",
      ],
      mistakes: [
        "Do not lift your hips off the floor",
        "Do not reach with your arms, use your stomach",
      ],
    },
    {
      id: "a5",
      name: "Bent-Knee Hip Raise",
      muscle: "abs",
      target: "Lower Abs",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Bent-Knee_Hip_Raise/0.jpg` },
      tip: "Focus on lifting your hips up, not just swinging your legs.",
      setupSteps: [
        "Lie flat on your back. Bend your knees. Lift your feet a little off the floor.",
        "Bring your knees to your chest. Lift your hips off the floor.",
        "Slowly go back to the start.",
      ],
      mistakes: [
        "Do not swing your legs to move",
        "Do not forget to lift your hips up",
      ],
    },
    {
      id: "a6",
      name: "Bottoms Up",
      muscle: "abs",
      target: "Lower Abs (Bodyweight)",
      sets: 3,
      reps: "10-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Bottoms_Up/0.jpg` },
      tip: "Control your legs coming down. Do not let them drop.",
      setupSteps: [
        "Lie on your back. Legs straight. Arms by your sides.",
        "Bring your knees to your chest. Then straighten your legs up.",
        "Lift your hips a little off the floor. Slowly bring them back down.",
      ],
      mistakes: [
        "Do not swing your legs to move",
        "Do not bend your lower back too much",
      ],
    },
    {
      id: "a7",
      name: "Barbell Side Bend",
      muscle: "abs",
      target: "Obliques",
      sets: 3,
      reps: "12-15 each side",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Side_Bend/0.jpg` },
      tip: "Use light weight. This is about slow, correct movement, not heavy lifting.",
      setupSteps: [
        "Stand and hold a bar on your shoulders, or a dumbbell by your side.",
        "Bend to the side as far as feels comfortable.",
        "Come back up straight. Do the same on the other side.",
      ],
      mistakes: [
        "Do not bend your knees or twist your body",
        "Do not use weight that is too heavy",
      ],
    },
    {
      id: "a8",
      name: "Barbell Ab Rollout",
      muscle: "abs",
      target: "Full Core (Advanced Beginner)",
      sets: 3,
      reps: "8-10",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Ab_Rollout/0.jpg` },
      tip: "Try this once planks feel easy for you. It is harder than the Ab Roller.",
      setupSteps: [
        "Kneel on the floor. Hold a light bar in front of you.",
        "Slowly roll the bar forward. Go as far as you can control.",
        "Pull yourself back to the start using your stomach muscles.",
      ],
      mistakes: [
        "Do not let your lower back drop",
        "Do not roll too far too soon",
      ],
    },
  ],

  legs: [
    {
      id: "l1",
      name: "Barbell Squat",
      muscle: "legs",
      target: "Quads, Glutes & Core Strength",
      sets: 3,
      reps: "8-10",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Full_Squat/0.jpg` },
      tip: "Keep knees aligned with toes as you descend.",
      setupSteps: [
        "Rest barbell across upper back/traps.",
        "Stand feet shoulder-width apart.",
        "Bend knees and hips to lower down until thighs are parallel to floor.",
        "Push through heels to return to standing position.",
      ],
      mistakes: ["Do not let knees cave inward", "Do not round your spine"],
    },
    {
      id: "l2",
      name: "Dumbbell Lunge",
      muscle: "legs",
      target: "Quads & Glutes Balance",
      sets: 3,
      reps: "10-12 each leg",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Dumbbell_Lunge/0.jpg` },
      tip: "Keep torso upright throughout step.",
      setupSteps: [
        "Stand holding dumbbells at sides.",
        "Step forward with one leg and lower hips until front knee is at 90 degrees.",
        "Push back to starting position.",
      ],
      mistakes: ["Do not let front knee extend past toes excessively"],
    },
    {
      id: "l3",
      name: "Leg Press",
      muscle: "legs",
      target: "Quads & Glutes (Guided)",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Sled_45_Degrees_Leg_Press/0.jpg`,
      },
      tip: "Do not lock out knees hard at top.",
      setupSteps: [
        "Sit on machine with feet hip-width on sled.",
        "Lower sled slowly toward chest.",
        "Press platform up through heels.",
      ],
      mistakes: ["Do not let lower back lift off pad"],
    },
    {
      id: "l4",
      name: "Romanian Deadlift",
      muscle: "legs",
      target: "Hamstrings & Glutes",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Barbell_Romanian_Deadlift/0.jpg`,
      },
      tip: "Hinge at hips while keeping back flat.",
      setupSteps: [
        "Hold barbell at hip level.",
        "Hinge forward at hips lowering bar along shins.",
        "Squeeze glutes to return tall.",
      ],
      mistakes: ["Do not round lower back"],
    },
    {
      id: "l5",
      name: "Standing Calf Raise",
      muscle: "legs",
      target: "Calves",
      sets: 3,
      reps: "15-20",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Standing_Calf_Raises/0.jpg` },
      tip: "Pause for 1 second at full extension.",
      setupSteps: [
        "Stand with balls of feet on step edge.",
        "Raise heels as high as possible.",
        "Lower heels below step level for full stretch.",
      ],
      mistakes: ["Do not bounce rapidly at bottom"],
    },
    {
      id: "l5",
      name: "Barbell Hip Thrust",
      muscle: "legs",
      target: "Glutes",
      sets: 3,
      reps: "10-12",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Hip_Thrust/0.jpg` },
      tip: "Use a pad on the bar. It makes this exercise much more comfortable.",
      setupSteps: [
        "Sit on the floor. Rest your upper back on a bench. Put the bar over your hips.",
        "Place your feet flat on the floor, hip-width apart.",
        "Push through your heels to lift your hips up until your body is straight.",
        "Slowly bring your hips back down.",
      ],
      mistakes: [
        "Do not bend your back too much at the top",
        "Do not push through your toes, use your heels",
      ],
    },
    {
      id: "l6",
      name: "Machine Leg Curl",
      muscle: "legs",
      target: "Hamstrings",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Lying_Leg_Curl/0.jpg` },
      tip: "Keep your hips pressed firmly against the bench throughout the entire movement to isolate the hamstrings.",
      setupSteps: [
        "Lie face down on the leg curl machine with the padded lever resting just below your calf muscles.",
        "Grasp the machine's handles for stability and align your knees with the machine's pivot point.",
        "Exhale as you curl your legs upward towards your glutes as far as comfortable without lifting your hips.",
        "Pause briefly at the top, then slowly lower the weight back to the starting position under control.",
      ],
      mistakes: [
        "Arching your lower back or lifting your hips off the pad to force the weight up",
        "Swinging the weight or using momentum instead of controlled hamstring tension",
      ],
    },
    {
      id: "l7",
      name: "Barbell Seated Calf Raise",
      muscle: "legs",
      target: "Calves",
      sets: 3,
      reps: "15-20",
      mediaType: "image",
      mediaSource: {
        uri: `${FREE_EXERCISE_DB}/Barbell_Seated_Calf_Raise/0.jpg`,
      },
      tip: "Stop and squeeze hard at the top of each rep.",
      setupSteps: [
        "Sit on a bench. Put the front of your feet on a raised block. Rest a padded bar on your knees.",
        "Lower your heels down as far as feels good.",
        "Rise up on your toes as high as you can.",
      ],
      mistakes: [
        "Do not move fast and bouncy, move slowly",
        "Do not make the movement too small",
      ],
    },
    {
      id: "l8",
      name: "Barbell Glute Bridge",
      muscle: "legs",
      target: "Glutes (Floor Variation)",
      sets: 3,
      reps: "12-15",
      mediaType: "image",
      mediaSource: { uri: `${FREE_EXERCISE_DB}/Barbell_Glute_Bridge/0.jpg` },
      tip: "A good first step before trying the barbell hip thrust.",
      setupSteps: [
        "Lie on your back. Bend your knees, feet flat. Rest the bar over your hips.",
        "Push through your heels to lift your hips until your body is straight.",
        "Squeeze your hips at the top. Then slowly come back down.",
      ],
      mistakes: [
        "Do not bend your lower back, use your hip muscles",
        "Do not stop before your hips are fully up",
      ],
    },
  ],
};

export default function ExercisesDataModule() {
  return null;
}
